<h3><a href="https://themlpath.com">< The ML Path</a></h3>

<h1>NumPy</h1>

## Introduction to NumPy

NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

### Why NumPy is Needed

- **Performance**: NumPy arrays are more efficient than Python lists because they require less memory and allow faster computation.
- **Vectorization**: NumPy allows for vectorized operations, meaning operations that can be applied element-wise without looping. This makes code cleaner and faster.
- **Convenience**: It provides many built-in functions for linear algebra, random number generation, and basic array operations, which makes it easier to work with data at scale.

### Difference Between NumPy Arrays and Python Lists

1. **Size**: NumPy arrays are more memory efficient than Python lists.
2. **Speed**: Operations on NumPy arrays are faster due to optimized, compiled C code running behind the scenes.
3. **Functionality**: NumPy arrays come with a wide variety of mathematical and statistical functions, while Python lists are limited in built-in functionality.

Let’s explore these differences by example.


In [2]:
# Install numpy

pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 202.6 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 1.7 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


## Comparing NumPy Arrays and Python Lists

In [3]:
import numpy as np

# Memory Efficiency
import sys

# Memory usage of Python list
python_list = list(range(1000))
print("Python list memory size:", sys.getsizeof(python_list), "bytes")

# Memory usage of NumPy array
numpy_array = np.arange(1000)
print("NumPy array memory size:", numpy_array.nbytes, "bytes")


# Speed Efficiency
import time

# Creating a large list and array
size = 1000000
python_list = list(range(size))
numpy_array = np.arange(size)

# Timing sum operation for Python list
start = time.time()
sum_list = sum(python_list)
print("Python list sum time:", time.time() - start, "seconds")

# Timing sum operation for NumPy array
start = time.time()
sum_array = np.sum(numpy_array)
print("NumPy array sum time:", time.time() - start, "seconds")


# Creating Arrays
# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

Python list memory size: 8056 bytes
NumPy array memory size: 8000 bytes
Python list sum time: 0.009281158447265625 seconds
NumPy array sum time: 0.0007276535034179688 seconds
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## More Ways of Creating NumPy Arrays

In [4]:
# 1. Creating an array with a range of values using arange()
arr_range = np.arange(0, 10, 2)  # Start at 0, go up to 10, step by 2
print("Array using arange():", arr_range)

# 2. Creating an array with evenly spaced values using linspace()
arr_linspace = np.linspace(0, 1, 5)  # 5 equally spaced values between 0 and 1
print("Array using linspace():", arr_linspace)

# 3. Creating an array filled with zeros
arr_zeros = np.zeros((3, 3))  # 3x3 array filled with zeros
print("Array of zeros:\n", arr_zeros)

# 4. Creating an array filled with ones
arr_ones = np.ones((2, 4))  # 2x4 array filled with ones
print("Array of ones:\n", arr_ones)

# 5. Creating an identity matrix using eye()
arr_eye = np.eye(4)  # 4x4 identity matrix
print("Identity matrix:\n", arr_eye)

# 6. Creating an array of random values between 0 and 1
arr_random = np.random.rand(3, 2)  # 3x2 array of random floats between 0 and 1
print("Random array:\n", arr_random)

# 7. Creating an array of random integers
arr_randint = np.random.randint(0, 100, (3, 3))  # 3x3 array of random integers between 0 and 100
print("Random integer array:\n", arr_randint)

# 8. Creating an array of a constant value
arr_full = np.full((2, 2), 7)  # 2x2 array filled with the value 7
print("Array of constant value:\n", arr_full)

# 9. Creating an array of equally spaced values (logarithmic scale) using logspace()
arr_logspace = np.logspace(0, 3, 4)  # 4 values between 10^0 and 10^3
print("Array using logspace():", arr_logspace)

# 10. Creating an uninitialized array (for performance)
arr_empty = np.empty((3, 3))  # 3x3 array with uninitialized values (whatever happens to be in memory)
print("Uninitialized array (empty):\n", arr_empty)


Array using arange(): [0 2 4 6 8]
Array using linspace(): [0.   0.25 0.5  0.75 1.  ]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random array:
 [[0.64469094 0.82379121]
 [0.30524902 0.12037909]
 [0.38201424 0.57361601]]
Random integer array:
 [[91 34 38]
 [ 3 49 19]
 [ 7 72 37]]
Array of constant value:
 [[7 7]
 [7 7]]
Array using logspace(): [   1.   10.  100. 1000.]
Uninitialized array (empty):
 [[6.94556252e-310 4.67592204e-310 6.94554568e-310]
 [6.94554568e-310 6.94554568e-310 6.94554568e-310]
 [6.94554568e-310 6.94554568e-310 6.94554568e-310]]
